"""add the credit ledger

`credit_ledger_transaction` (T8), `credit_balance_snapshot` (T10) and `workspace_category`
(T6). The ledger is append-only, with debits stored negative and grants positive.
`credit_balance_snapshot` has no writer yet; `CreditLedgerTransaction.balance` is correct
without one.

`policy_id` and `category` are nullable because a grant is not priced.
`ck_credit_ledger_transaction_debit_is_priced` states the invariant that does hold.

The enum is created and dropped by hand. Alembic autogenerates neither end of its life cycle:
`create_table` creates the type as a side effect but `drop_table` leaves it behind, so an
autogenerated downgrade fails the next upgrade with `type "transaction_type" already exists`.
The column is declared `create_type=False` so the implicit create does not fire as well.

The downgrade is real: every table here is new and empty on the way in.

Revision ID: 0b4b174175ad
Revises: 30ac7fce87ae
Create Date: 2026-09-09
"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel maps str to AutoString, which autogenerate writes into revisions without importing.
# The submodule is named explicitly because sqlmodel/__init__.py does not re-export `sql`.
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0b4b174175ad"
down_revision: str | None = "30ac7fce87ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Spelled out rather than imported from models.py, so a later edit to TransactionType cannot
# rewrite what this revision created. postgresql.ENUM for `create_type=False`, which suppresses
# only the implicit DDL; .create() and .drop() below still work.
TRANSACTION_TYPE = postgresql.ENUM("debit", "grant", "reversal", name="transaction_type", create_type=False)

# One original debit per billing event, while still allowing correction rows against that same
# event (T18). Repeated in the downgrade because op.drop_index needs it to identify the index.
ORIGINAL_DEBIT_WHERE = sa.text("correction_batch_id IS NULL AND transaction_type = 'debit'")


def upgrade() -> None:
    # Before the table that uses it.
    TRANSACTION_TYPE.create(op.get_bind())

    op.create_table(
        "credit_ledger_transaction",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user", sa.Uuid(), nullable=True),
        sa.Column("transaction_type", TRANSACTION_TYPE, nullable=False),
        sa.Column("credits", sa.Numeric(), nullable=False),
        sa.Column("billing_event_id", sa.Uuid(), nullable=True),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("occurred_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("reverses_id", sa.Uuid(), nullable=True),
        # No foreign key: T17 adds the `correction_batch` table and the constraint with it.
        # The column exists now because the idempotency index below tests it.
        sa.Column("correction_batch_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.CheckConstraint(
            "transaction_type <> 'debit' OR (policy_id IS NOT NULL AND category IS NOT NULL)",
            name=op.f("ck_credit_ledger_transaction_debit_is_priced"),
        ),
        sa.ForeignKeyConstraint(
            ["billing_event_id"],
            ["billing_event.uuid"],
            name=op.f("fk_credit_ledger_transaction_billing_event_id_billing_event"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["billing_item.uuid"], name=op.f("fk_credit_ledger_transaction_item_id_billing_item")
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["pricing_policy.uuid"], name=op.f("fk_credit_ledger_transaction_policy_id_pricing_policy")
        ),
        sa.ForeignKeyConstraint(
            ["reverses_id"],
            ["credit_ledger_transaction.uuid"],
            name=op.f("fk_credit_ledger_transaction_reverses_id_credit_ledger_transaction"),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_credit_ledger_transaction")),
    )
    op.create_index(
        "credit_ledger_original_debit_index",
        "credit_ledger_transaction",
        ["billing_event_id"],
        unique=True,
        postgresql_where=ORIGINAL_DEBIT_WHERE,
    )
    op.create_index(
        "credit_ledger_workspace_recorded_index",
        "credit_ledger_transaction",
        ["workspace", "recorded_at"],
        unique=False,
    )

    op.create_table(
        "credit_balance_snapshot",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user", sa.Uuid(), nullable=True),
        sa.Column("as_of", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("balance", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_credit_balance_snapshot")),
        # NULLS NOT DISTINCT so the whole-pool row, which has a null user, stays unique. By
        # default PostgreSQL treats two null users as different values and would let the same
        # workspace and instant be snapshotted more than once.
        sa.UniqueConstraint(
            "workspace",
            "user",
            "as_of",
            name=op.f("uq_credit_balance_snapshot_workspace"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "credit_balance_snapshot_lookup_index",
        "credit_balance_snapshot",
        ["workspace", "user", "as_of"],
        unique=False,
    )

    op.create_table(
        "workspace_category",
        sa.Column("workspace", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("workspace", name=op.f("pk_workspace_category")),
    )


def downgrade() -> None:
    """Reversible, unlike the three revisions before it.

    Every table here is new and empty on the way in, so dropping them loses nothing that
    existed before this revision - which is what makes a real downgrade worth writing where
    30ac7fce87ae's had to be empty.
    """
    op.drop_table("workspace_category")

    op.drop_index("credit_balance_snapshot_lookup_index", table_name="credit_balance_snapshot")
    op.drop_table("credit_balance_snapshot")

    op.drop_index("credit_ledger_workspace_recorded_index", table_name="credit_ledger_transaction")
    op.drop_index(
        "credit_ledger_original_debit_index",
        table_name="credit_ledger_transaction",
        postgresql_where=ORIGINAL_DEBIT_WHERE,
    )
    op.drop_table("credit_ledger_transaction")

    # After the table, and the reason this downgrade is written by hand: drop_table does not
    # drop the type, so without this the next upgrade fails on a type that already exists.
    TRANSACTION_TYPE.drop(op.get_bind())
