"""baseline schema

Revision ID: 20fef2107e45
Revises:
Create Date: 2026-08-20 14:33:08.378024

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20fef2107e45"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_item",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_billing_item")),
    )
    op.create_index(op.f("ix_billing_item_sku"), "billing_item", ["sku"], unique=False)
    op.create_table(
        "workspace_account",
        sa.Column("workspace", sa.String(), nullable=False),
        sa.Column("account", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("workspace", name=op.f("pk_workspace_account")),
    )
    op.create_index(op.f("ix_workspace_account_account"), "workspace_account", ["account"], unique=False)
    op.create_index(op.f("ix_workspace_account_workspace"), "workspace_account", ["workspace"], unique=False)
    op.create_table(
        "billing_event",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("event_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("event_end", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("user", sa.Uuid(), nullable=True),
        sa.Column("workspace", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.CheckConstraint("event_start <= event_end", name=op.f("ck_billing_event_start_before_end")),
        sa.ForeignKeyConstraint(
            ["item_id"], ["billing_item.uuid"], name=op.f("fk_billing_event_item_id_billing_item")
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_billing_event")),
    )
    op.create_index(
        "billingevent_workspace_eventstart_index", "billing_event", ["workspace", "event_start"], unique=False
    )
    # Written by hand: these are in UNCOMPARED_INDEXES in alembic/env.py, so
    # autogenerate does not emit them. PostgreSQL only.
    op.create_index(
        "billingevent_day_aggregate_index",
        "billing_event",
        [
            sa.literal_column("date_trunc('day', event_start AT TIME ZONE 'UTC')"),
            sa.literal_column("(date_trunc('day', event_start AT TIME ZONE 'UTC') + '1 day'::interval)"),
            "workspace",
            "item_id",
        ],
        unique=False,
    )
    op.create_index(
        "billingevent_month_aggregate_index",
        "billing_event",
        [
            sa.literal_column("date_trunc('month', event_start AT TIME ZONE 'UTC')"),
            sa.literal_column("(date_trunc('month', event_start AT TIME ZONE 'UTC') + '1 month'::interval)"),
            "workspace",
            "item_id",
        ],
        unique=False,
    )

    op.create_table(
        "billing_item_price",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("valid_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("valid_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("configured_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_from <= valid_until", name=op.f("ck_billing_item_price_validity_order")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["billing_item.uuid"], name=op.f("fk_billing_item_price_item_id_billing_item")
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_billing_item_price")),
    )
    op.create_index(
        "billingitemprice_item_validfrom_index", "billing_item_price", ["item_id", "valid_from"], unique=False
    )
    op.create_table(
        "billing_resource_consumption_rate_sample",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("sample_time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("user", sa.Uuid(), nullable=True),
        sa.Column("workspace", sa.String(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["billing_item.uuid"],
            name=op.f("fk_billing_resource_consumption_rate_sample_item_id_billing_item"),
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_billing_resource_consumption_rate_sample")),
    )
    op.create_index(
        "billableresourceconsumptionratesample_workspace_time_index",
        "billing_resource_consumption_rate_sample",
        ["workspace", "sample_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_resource_consumption_rate_sample_sample_time"),
        "billing_resource_consumption_rate_sample",
        ["sample_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_billing_resource_consumption_rate_sample_sample_time"),
        table_name="billing_resource_consumption_rate_sample",
    )
    op.drop_index(
        "billableresourceconsumptionratesample_workspace_time_index",
        table_name="billing_resource_consumption_rate_sample",
    )
    op.drop_table("billing_resource_consumption_rate_sample")
    op.drop_index("billingitemprice_item_validfrom_index", table_name="billing_item_price")
    op.drop_table("billing_item_price")
    op.drop_index("billingevent_workspace_eventstart_index", table_name="billing_event")
    op.drop_index("billingevent_month_aggregate_index", table_name="billing_event")
    op.drop_index("billingevent_day_aggregate_index", table_name="billing_event")
    op.drop_table("billing_event")
    op.drop_index(op.f("ix_workspace_account_workspace"), table_name="workspace_account")
    op.drop_index(op.f("ix_workspace_account_account"), table_name="workspace_account")
    op.drop_table("workspace_account")
    op.drop_index(op.f("ix_billing_item_sku"), table_name="billing_item")
    op.drop_table("billing_item")
    # ### end Alembic commands ###
