"""Alembic environment for accounting-service.

The database URL comes from accounting_service.settings rather than from
alembic.ini, so migrations always target the same database as the application.
PostgreSQL only.
"""

from logging.config import fileConfig
from typing import Any

from sqlalchemy import create_engine, pool

from accounting_service import settings

# Imported from models rather than from sqlmodel directly. It is the same object, but taking it
# from here means this module is imported, and importing it is what defines the table classes
# that populate the metadata. Read it off SQLModel instead and the import is unused, an import
# cleanup removes it, and autogenerate then sees an empty schema and offers to drop every table.
from accounting_service.models import metadata
from alembic import context

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = metadata

# PostgreSQL rewrites index expressions when it stores them, adding casts and
# parentheses, and Alembic compares them as strings. So these two always look
# changed and every autogenerated revision would drop and recreate them.
#
# Excluding them has a cost that needs care: include_object governs rendering as
# well as comparison, so an index named here is left out of generated revisions
# too, and `alembic check` reports CLEAN when it is missing from the schema. That
# has happened once already - a regenerated baseline dropped both indexes and the
# check said nothing.
#
# These two are therefore written by hand in the baseline revision. If you
# regenerate it, re-add them and confirm by reading the SQL, not by running
# `alembic check`. Anything added to this list inherits the same problem.
UNCOMPARED_INDEXES = frozenset(
    {
        "billingevent_day_aggregate_index",
        "billingevent_month_aggregate_index",
    }
)


def include_object(_object, name, type_, _reflected, _compare_to) -> bool:  # noqa: ANN001
    """Alembic passes these positionally, so the unused ones keep their place."""
    if type_ == "index" and name in UNCOMPARED_INDEXES:
        return False

    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it, for review or manual application."""
    context.configure(
        url=settings.get_db_url().render_as_string(hide_password=False),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def _run(connection: Any) -> None:  # noqa: ANN401
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Connect to the database and run the migrations against it.

    A caller can inject an open connection through config.attributes, which lets
    migrations run against a database other than the one settings names. The
    caller owns the transaction in that case.
    """
    injected = config.attributes.get("connection")

    if injected is not None:
        _run(injected)
        return

    connectable = create_engine(
        settings.get_db_url(),
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        _run(connection)


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
