"""Alembic environment for accounting-service.

The database URL comes from accounting_service.db_settings rather than from
alembic.ini, so migrations always target the same database as the application.

Note that accounting_service.models chooses some indexes based on the driver in
use (see the is_sqlite() guards in models.py). Autogenerate therefore reflects
whichever driver SQL_DRIVER names when it runs. Generate migrations with
SQL_DRIVER set to postgresql+psycopg, or PostgreSQL-only indexes will be
silently missing from the revision.
"""

from logging.config import fileConfig
from typing import Any

from sqlalchemy import create_engine, pool

from accounting_service import db_settings, models
from alembic import context

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = models.Base.metadata

# PostgreSQL rewrites index expressions when it stores them, adding explicit
# casts and parentheses: date_trunc('day', event_start AT TIME ZONE 'UTC')
# comes back as date_trunc('day'::text, (event_start AT TIME ZONE 'UTC'::text)).
# Alembic compares those as strings, so these indexes always look changed and
# every autogenerated revision would drop and recreate them for no reason.
#
# They are excluded from comparison instead.
#
# IMPORTANT: include_object governs rendering as well as comparison, so an index
# named here is left out of generated revisions too. These two are written by
# hand in the baseline revision. Add any new entry to a migration yourself, and
# do not expect alembic check to notice if one goes missing.
UNCOMPARED_INDEXES = frozenset(
    {
        "billingevent_day_aggregate_index",
        "billingevent_month_aggregate_index",
    }
)


def include_object(_object, name, type_, _reflected, _compare_to) -> bool:  # noqa: ANN001
    """Alembic passes these positionally, so the unused ones keep their place."""
    if type_ == "index" and name in UNCOMPARED_INDEXES:
        return False

    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it, for review or manual application."""
    context.configure(
        url=db_settings.get_db_url().render_as_string(hide_password=False),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def _run(connection: Any) -> None:  # noqa: ANN401
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Connect to the database and run the migrations against it.

    A caller can inject an open connection through config.attributes, which lets
    migrations run against a database other than the one db_settings names. The
    integration tests use this to migrate a throwaway database; the caller owns
    the transaction in that case.
    """
    injected = config.attributes.get("connection")

    if injected is not None:
        _run(injected)
        return

    connectable = create_engine(
        db_settings.get_db_url(),
        connect_args=db_settings.connect_args,
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        _run(connection)


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
